content = {
    title : 'Building Careers',
    intro : '<p><span>Hello!</span><br>I am <span>Srishti Sawla</span><br>I am a data scientist with experience in analytics and data science in <span>banking and insurance domain</span><br> I like getting people excited about numbers and the insights the data carries.<br></p>',
    outro : '<p>Outside office, I am a data science enthusiast with a mission to help individuals build their <span>successful careers</span> in data science.<br> I conduct data science <span>online courses</span> for interested individuals (freshers/experienced) who want to <span>build a solid foundation</span> and aim towards accelerating their career in this field.</p>',
    course : 'Courses',
    cintro : '<p><span class="big">Data Science Trilogy</span><br>is a complete hands-on course for learning all the aspects of data science used in industry from scratch.<br>This course is stitched in such a way that it covers the needs of every individual.<br>The goal of this course is to simplify the concepts of data science for candidates who aspire to become successful data scientists but get confused and stuck by seeing huge and complicated resources online. <br>Data Science Trilogy divides the course into three important modules - The Stage, The Trick and The Prestige</p>',
    cstage : '<p><span class="big">THE STAGE</span><br>This module will help the candidates to set a stage for their data science career by giving them an overview of data and how to play with the data for generating useful insights which can benefit the business in numerous ways.</p>',
    ctrick : '<p><span class="big">THE TRICK</span><br>This module will help the candidates to perform the exact trick required to grow the business by applying different machine learning algorithms on the data available and give valuable predictions.</p>',
    cprestige : '<p><span class="big">THE PRESTIGE</span><br>This module will help the candidates to learn advanced concepts of machine learning and build 2 complete projects from scratch using their overall learnings and thereby making them fit for data industry.</p>',
    csyllabus : '<p><span class="big">Course Curriculum</span><br><br><span class="mild">The Stage (Data Analytics) :</span><br> Topics Covered : Setting up the environment, data cleaning, data manipulation and visualisation<br>Toolbox : Git, Visual Studio Code, Statistics<br> Tech Stack : MS SQL,Basic python,numpy,pandas,beautiful soup,matplotlib,seaborn and other related packages<br><br><span class="mild">The Trick (Machine Learning) :</span><br> Topics Covered : Mathematics for data science,supervised algorithms,unsupervised algorithms <br>Tech Stack : Various python libraries for basic and advanced algorithms.<br><br><span class="mild"> The Prestige (Advanced Machine Learning) :</span><br> Advanced Machine Learning Algorithms : Ensembling techniques,NLP,recommender systems<br> 2 Capstone Projects : Building complete domain based industry projects from scratch</p>',
    cpricing : '<p><span class="big">Course Duration and Fees</span><br>Total Course Duration : 200 days<br> Batch Starts From : 3-August-2020<br><span class="mild">Fees:</span><br>The Stage : INR 7,000 only<br> The Trick : INR 10,000 only<br> The Prestige : INR 13,000 only<br> Payment Methods: One time complete payment of the whole course OR Module wise payment also accepted</p>',
    cschedule : '<p><span class="big">CLASS SCHEDULE :</span><br>2 hours Class will be conducted on Monday, Wednesday and Friday every week from 9pm to 11pm IST</p>',
    cenrollment : '<p><span class="big">Enrollment Process :</span><br>For enrolling yourself into the course or any other inquires,please drop a mail at contact@srishtisawla.com with your details including work experience and why do you aspire a career in this field. I will personally shortlist students and futher details will be communicated over mail.</p>',
    ccontact : '<p><span class="big">Contact:</span><br>Drop me a mail at contact@srishtisawla.com</p>'
}